import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {type: 'doc', id: "intro", label: "Справочный центр ТРИК"},
    {type: 'doc', id: "studio/about/index", label: "О TRIK Studio"},
    {type: 'doc', id: "studio/about/version", label: "Как узнать версию TRIK Studio"},
    {type: 'doc', id: "studio/start", label: "Начало работы и создание проекта"},
    {type: 'doc', id: "studio/interface/index", label: "Интерфейс TRIK Studio"},
    {type: 'doc', id: "studio/interface/main-menu", label: "Главное меню TRIK Studio"},
    {type: 'doc', id: "studio/interface/graphics", label: "Работа с графиками"},
    {type: 'doc', id: "studio/interface/faq-robot-settings", label: "Как открыть настройки робота?"},
    {type: 'doc', id: "studio/interface/language", label: "Как изменить язык интерфейса TRIK Studio?"},
    {type: 'doc', id: "studio/settings", label: "Настройки TRIK Studio"},
    {type: 'doc', id: "studio/2d-model/index", label: "2D-модель"},
    {type: 'doc', id: "studio/2d-model/settings", label: "Гибкая настройка 2D-модели"},
    {type: 'doc', id: "studio/2d-model/restrictions/index", label: "Добавление ограничений в 2D-модель"},
    {type: 'doc', id: "studio/2d-model/restrictions/examples", label: "Примеры задания ограничений"},
    {type: 'doc', id: "studio/programming-visual/index", label: "Программирование на визуальном языке"},
    {type: 'doc', id: "studio/programming-visual/blocks-add-delete", label: "Добавление и удаление блоков"},
    {type: 'doc', id: "studio/programming-visual/blocks", label: "Общие блоки"},
    {type: 'doc', id: "studio/programming-visual/connection-between-blocks", label: "Связи между блоками"},
    {type: 'doc', id: "studio/programming-visual/expression-syntax/index", label: "Синтаксис выражений в блоках"},
    {type: 'doc', id: "studio/programming-visual/expression-syntax/types/index", label: "Типы языка TRIK Studio"},
    {type: 'doc', id: "studio/programming-visual/expression-syntax/types/array", label: "Массив"},
    {type: 'doc', id: "studio/programming-visual/expression-syntax/lexemes", label: "Лексемы языка TRIK Studio"},
    {type: 'doc', id: "studio/programming-visual/expression-syntax/operators", label: "Операторы языка TRIK Studio"},
    {type: 'doc', id: "studio/programming-visual/expression-syntax/const", label: "Константы"},
    {type: 'doc', id: "studio/programming-visual/expression-syntax/sensory-variables", label: "Сенсорные переменные"},
    {type: 'doc', id: "studio/programming-visual/expression-syntax/built-in-functions", label: "Встроенные функции"},
    {type: 'doc', id: "studio/programming-visual/editing-element-properties", label: "Редактирование свойств элементов"},
    {type: 'doc', id: "studio/programming-visual/subprograms", label: "Подпрограммы"},
    {type: 'doc', id: "studio/programming-code", label: "Программирование на текстовом языке"},
    {type: 'doc', id: "studio/exercises", label: "Упражнения"},
    {type: 'doc', id: "studio/utilities/index", label: "Сторонние утилиты"},
    {type: 'doc', id: "studio/utilities/putty", label: "PuTTY"},
    {type: 'doc', id: "studio/utilities/winscp", label: "WinSCP"},
    {type: 'doc', id: "studio/shortcuts", label: "Горячие клавиши в TRIK Studio"},
    {type: 'doc', id: "studio/antivirus-conflicts/index", label: "Сбои из-за антивирусов"},
    {type: 'doc', id: "studio/antivirus-conflicts/avast", label: "Антивирус Avast блокирует TRIK Studio. Что делать?"},
    {type: 'doc', id: "trik-studio-junior/about/index", label: "О TRIK Studio Junior"},
    {type: 'doc', id: "trik-studio-junior/about/version", label: "Как узнать версию TRIK Studio Junior"},
    {type: 'doc', id: "trik-studio-junior/start", label: "Начало работы и создание проекта в TRIK Studio Junior"},
    {type: 'doc', id: "trik-studio-junior/interfeis-trik-studio-junior/index", label: "Интерфейс TRIK Studio Junior"},
    {type: 'doc', id: "trik-studio-junior/interfeis-trik-studio-junior/robot-image-change", label: "Как заменить изображение «Исполнителя» в TRIK Studio Junior?"},
    {type: 'doc', id: "trik-studio-junior/2d-model", label: "2D-модель в TRIK Studio Junior"},
    {type: 'doc', id: "trik-studio-junior/settings", label: "Настройки TRIK Studio Junior"},
    {type: 'doc', id: "trik-studio-junior/programming/index", label: "Программирование на визуальном языке в TRIK Studio Junior"},
    {type: 'doc', id: "trik-studio-junior/programming/blocks-add-delete", label: "Добавление и удаление блоков в TRIK Studio Junior"},
    {type: 'doc', id: "trik-studio-junior/programming/blocks", label: "Блоки в TRIK Studio Junior"},
    {type: 'doc', id: "trik-studio-junior/programming/connection-between-blocks", label: "Связи между блоками в TRIK Studio Junior"},
    {type: 'doc', id: "trik-studio-junior/programming/expression-syntax", label: "Синтаксис выражений в блоках в TRIK Studio Junior"},
    {type: 'doc', id: "trik-studio-junior/programming/editing-element-properties", label: "Редактирование свойств элементов в TRIK Studio Junior"},
    {type: 'doc', id: "trik-studio-junior/programming/subprograms", label: "Подпрограммы в TRIK Studio Junior"},
    {type: 'doc', id: "trik-studio-junior/exercises", label: "Упражнения в TRIK Studio Junior"},
    {type: 'doc', id: "integrations/pycharm/index", label: "PyCharm"},
    {type: 'doc', id: "integrations/pycharm/running-2d-model-in-trik-studio-from-pycharm", label: "Запуск 2D-модели в TRIK Studio из PyCharm"},
    {type: 'doc', id: "integrations/sublime/index", label: "Sublime Text"},
    {type: 'doc', id: "integrations/sublime/run-2d-from-sublime", label: "Запуск 2D-модели в TRIK Studio из Sublime Text"},
    {type: 'doc', id: "integrations/sublime/loading-programs-on-several-robots", label: "Загрузка программ на нескольких роботов ТРИК из Sublime Text"},
    {type: 'doc', id: "integrations/vscode/index", label: "VSCode"},
    {type: 'doc', id: "integrations/vscode/run-2d-from-vscode", label: "Запуск 2D-модели в TRIK Studio из VSCode"},
    {type: 'doc', id: "integrations/vscode/loading-programs-on-several-robots", label: "Загрузка программ на нескольких роботов ТРИК из VSCode"},
    {type: 'doc', id: "trik/about/index", label: "О контроллере ТРИК"},
    {type: 'doc', id: "trik/about/screenshot", label: "Скриншот экрана контроллера ТРИК"},
    {type: 'doc', id: "trik/firmware/index", label: "Обновление встроенного программного обеспечения контроллера ТРИК"},
    {type: 'doc', id: "trik/firmware/version", label: "Как узнать версию встроенного ПО контроллера ТРИК?"},
    {type: 'doc', id: "trik/menu", label: "Меню контроллера ТРИК"},
    {type: 'doc', id: "trik/wi-fi/index", label: "Подключения по Wi-Fi к контроллеру ТРИК"},
    {type: 'doc', id: "trik/wi-fi/network-connection", label: "Подключение контроллера ТРИК к компьютеру и смартфону"},
    {type: 'doc', id: "trik/wi-fi/connect-to-ts", label: "Подключение контроллера ТРИК к TRIK Studio"},
    {type: 'doc', id: "trik/wi-fi/interaction/index", label: "Взаимодействие контроллеров ТРИК"},
    {type: 'doc', id: "trik/wi-fi/interaction/interaction-example", label: "Пример решения задачи по взаимодействию двух роботов"},
    {type: 'doc', id: "trik/uart", label: "Подключение к контроллеру ТРИК с помощью UART"},
    {type: 'doc', id: "trik/run-upload-programs", label: "Запуск программ и их загрузка на контроллер ТРИК"},
    {type: 'doc', id: "trik/programming-visual/index", label: "Программирование ТРИК на визуальном языке"},
    {type: 'doc', id: "trik/programming-visual/blocks", label: "Блоки ТРИК"},
    {type: 'doc', id: "trik/programming-visual/sensory-variables", label: "Сенсорные переменные для контроллера ТРИК"},
    {type: 'doc', id: "trik/programming-code/index", label: "Программирование ТРИК на Python и JavaScript"},
    {type: 'doc', id: "trik/programming-code/object-brick/index", label: "Объект «brick»"},
    {type: 'doc', id: "trik/programming-code/object-brick/class-accelerometer", label: "Класс «accelerometer»"},
    {type: 'doc', id: "trik/programming-code/object-brick/class-battery", label: "Класс «battery»"},
    {type: 'doc', id: "trik/programming-code/object-brick/class-colorsensor", label: "Класс «colorSensor»"},
    {type: 'doc', id: "trik/programming-code/object-brick/class-display", label: "Класс «display»"},
    {type: 'doc', id: "trik/programming-code/object-brick/class-encoder", label: "Класс «encoder»"},
    {type: 'doc', id: "trik/programming-code/object-brick/class-gyroscope", label: "Класс «gyroscope»"},
    {type: 'doc', id: "trik/programming-code/object-brick/class-keys", label: "Класс «keys»"},
    {type: 'doc', id: "trik/programming-code/object-brick/class-led", label: "Класс «led»"},
    {type: 'doc', id: "trik/programming-code/object-brick/class-linesensor", label: "Класс «lineSensor»"},
    {type: 'doc', id: "trik/programming-code/object-brick/class-motor", label: "Класс «motor»"},
    {type: 'doc', id: "trik/programming-code/object-brick/class-objectsensor", label: "Класс «objectSensor»"},
    {type: 'doc', id: "trik/programming-code/object-brick/class-marker", label: "Класс «marker»"},
    {type: 'doc', id: "trik/programming-code/object-brick/class-sensor", label: "Класс «sensor»"},
    {type: 'doc', id: "trik/programming-code/object-brick/class-ircamera", label: "Класс «irCamera»"},
    {type: 'doc', id: "trik/programming-code/object-script", label: "Объект «script»"},
    {type: 'doc', id: "trik/programming-code/object-mailbox", label: "Объект «mailbox»"},
    {type: 'doc', id: "trik/programming-code/object-gamepad", label: "Объект «gamepad»"},
    {type: 'doc', id: "trik/programming-code/object-threading", label: "Объект «Threading»"},
    {type: 'doc', id: "trik/programming-code/function-getphoto", label: "Функция getPhoto"},
    {type: 'doc', id: "trik/programming-code/function-include", label: "Функция include"},
    {type: 'doc', id: "trik/web-interface", label: "Веб-интерфейс контроллера ТРИК"},
    {type: 'doc', id: "trik/work-with-devices/index", label: "Подключение устройств к ТРИК и работа с ними"},
    {type: 'doc', id: "trik/work-with-devices/video", label: "Подключение и работа с видеомодулем"},
    {type: 'doc', id: "trik/work-with-devices/testing-connected-devices", label: "Тестирование подключенных к контроллеру ТРИК устройств"},
    {type: 'doc', id: "trik/work-with-devices/usb-camera", label: "Настройка работы USB-камеры с контроллером ТРИК"},
    {type: 'doc', id: "trik/work-with-devices/capture-images-on-camera", label: "Съемка изображений на камеру ТРИК и использование их в TRIK Studio"},
    {type: 'doc', id: "trik/work-with-devices/battery-and-charger", label: "Работа с аккумулятором и зарядным устройством"},
    {type: 'doc', id: "trik/work-with-devices/podklyuchenie-usb-wi-fi-adaptera-k-kontrolleru-trik", label: "Подключение USB Wi-Fi адаптера к контроллеру ТРИК"},
    {type: 'doc', id: "ev3/about", label: "O LEGO EV3"},
    {type: 'doc', id: "ev3/connect-to-studio", label: "Подключение контроллера LEGO EV3 к TRIK Studio"},
    {type: 'doc', id: "ev3/blocks", label: "Блоки LEGO EV3"},
    {type: 'doc', id: "ev3/sensory-variables", label: "Сенсорные переменные для контроллера LEGO EV3"},
    {type: 'doc', id: "ev3/run-upload-programs", label: "Запуск программ и их загрузка на контроллер LEGO EV3"},
    {type: 'doc', id: "ev3/ts-for-vrt", label: "Программирование LEGO EV3 для Virtual Robotics Toolkit в TRIK Studio"},
    {type: 'doc', id: "nxt/about", label: "О LEGO NXT"},
    {type: 'doc', id: "nxt/firmware", label: "Прошивка контроллера LEGO NXT"},
    {type: 'doc', id: "nxt/connect-to-studio", label: "Подключение контроллера LEGO NXT к TRIK Studio"},
    {type: 'doc', id: "nxt/blocks", label: "Блоки LEGO NXT"},
    {type: 'doc', id: "nxt/sensory-variables", label: "Сенсорные переменные для контроллера LEGO NXT"},
    {type: 'doc', id: "nxt/c", label: "Программирование LEGO NXT на C"},
    {type: 'doc', id: "nxt/run-upload-programs", label: "Запуск программ и их загрузка на контроллер LEGO NXT"},
    {type: 'doc', id: "pioneer/about", label: "О квадрокоптере Геоскан Пионер"},
    {type: 'doc', id: "pioneer/blocks", label: "Блоки квадрокоптера Геоскан Пионер"},
    {type: 'doc', id: "gamepad/about/index", label: "О TRIK Gamepad"},
    {type: 'doc', id: "gamepad/about/app", label: "Приложение TRIK Gamepad"},
    {type: 'doc', id: "gamepad/about/utility", label: "Утилита TRIK Gamepad"},
    {type: 'doc', id: "gamepad/remote-control", label: "Управление роботом с пульта"},
    {type: 'doc', id: "feedback/logging", label: "Действия при неправильной работе TRIK Studio или контроллера ТРИК"}
  ],
};

export default sidebars;
